---
- name: Installation de Docker sur les instances AWS
  hosts: all
  become: yes  # On utilise sudo pour les installations
  
  tasks:
    - name: Mettre à jour le cache des paquets (apt update)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Installer les dépendances système
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Installer Docker et Docker-Compose
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Démarrer et activer le service Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ajouter l'utilisateur ubuntu au groupe docker
      user:
        name: ubuntu
        groups: docker
        append: yes